version: '3'

services: 
  web: 
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - 3000
      - 4000
    volumes:
      - ./docker-bot:/usr/src/app 
      - /usr/src/app/node_modules